/** 无关名称模式（明文存储，非敏感） */
export const JUNK_NAME_PATTERNS: RegExp[] = [
  /备案/i, /beian/i, /icp/i, /公网安备/i,
  /^(Astro|Hexo|Valaxy|Halo|Vue(\.js)?|React|Next\.js|Nuxt|Hugo|WordPress|Typecho)$/i,
  /^(Butterfly|Volantis|Fluid|Clarity|Pure|Waline|Twikoo|Giscus)$/i,
  /^(Theme:?\s|主题:)/i,
  /^Markdown Guide$/i,
  /^(Vercel|Cloudflare|Netlify|EdgeOne)$/i,
  /^(QQ|QQ群\s*\d+|GitHub|Github|Gitee|GitLab|GitCode|Codeberg|Coding|SourceForge|Twitter|知乎|B站|哔哩哔哩|bilibili|BiliBili|BiliBiBi|网易云音乐)$/i,
  /^(百度|Bing|Google|搜狗|360搜索|必应)$/i,
  /^(Sponsor|赞助|Donate)/i,
  /^开往$/i, /^Travelling$/i,
  /^(订阅|RSS|Feed)/i,
  /^(订阅本文评论|订阅本站评论)$/i,
  /^萌ICP备/i,
  /盟\d{6,}号|AIA盟|KUCAT盟|ICP备.*号|备案.*号/i,
  /^(项目主页|Create A Pull Request|Visit)$/i,
  /本站|本网站|本博客/i,
  /^(友链|友情链接|申请友链|Links?|申请链接)$/i,
  /^(首页|关于|关于我|about|home)$/i,
  /^(404|页面未找到|Redirect|Redirecting)$/i,
  /^Theme by|^Powered by|^Proudly powered/i,
  /图床|网盘|CDN|短链|短网址|云盘|存储/,
  /监控|Monitor|Status|Uptime|状态/,
  /文件加速|加速|API接口|接口/,
  /工具|助手|导航/,
  /随机|开往项目/i,
  /^(Halo|WordPress|Typecho|Z-Blog|Discuz|PHPWind|DedeCMS|帝国CMS)$/i,
  /WordPress|主题|插件|模板|主题商店/i,
  /^(站长|论坛|社区|交流|BBS)/i,
  /^(社区|论坛|交流群|QQ群|微信群|广场|书苑|书库|LINUX\s*DO|Linuxcat|归档站|归档)/i,
  /^(游戏|试玩|娱乐|赌博|博彩|棋牌|Slot|Casino)/i,
  /^(Steam|Epic|Origin|Uplay|Battle\.net|Xbox|PlayStation|Nintendo|任天堂|索尼|微软游戏)/i,
  /^(公司|印刷|广告|设计|装修|建筑|工程|劳务|派遣)/i,
  /^(支付|收款|码支付|POS|刷卡|收银)/i,
  /^(马克思主义|列宁|毛泽东|邓小平|共产党|社会主义|资本主义|意识形态|政治)/i,
  /^(教程|指南|指引|入门|手册|文档|帮助|FAQ|CheatSheet|速查)/i,
  /^(Vue|React|Angular|Node\.?js|Python|Java|Go|Rust|Docker|Kubernetes)(\s|\d|\.)/i,
  /^(流量卡|神卡|大流量|号卡|套餐|宽带|物联网卡)/i,
  /^(资源|资源站|下载|分享站|破解|绿色版|汉化)/i,
  /源码|原码|程序源码|网站源码|系统源码/i,
  /^(评测|测评|体验|软件评测|APP评测)/i,
  /图鉴|年鉴|统计|数据|大全|百科|图库/i,
  /^(云服务器|云主机|云服务|云服务商|VPS|服务器|主机|域名|CDN|云存储|对象存储|阿里云|腾讯云|华为云)/i,
  /^(导航|网址导航|导航站|分类导航|收藏夹|书签)/i,
  /^(新闻|资讯|热点|快讯|头条|时政|要闻)/i,
  /热榜|热门|热搜|排行榜|榜单/i,
  /^(文库|文档|资料库|知识库|百科|维基)/i,
  /^(相册|音乐|歌单|专辑|画廊|摄影|图片)/i,
  /^(画图|绘画|画画|涂鸦|插画|绘图)/i,
  /^(更新日志|更新|日志|更新记录|Changelog)$/i,
  /^(文档|博客框架|框架|框架版本)/i,
  /^(抖音|Youtube|YouTube)$/i,
  /^(微信红包|红包|封面|优惠|促销|购物|淘宝|天猫|京东|拼多多|闲鱼|转转|商城|店铺|商店|下单|购买)/i,
  /^(借款|贷款|借贷|金融|理财|投资|信用贷|网贷)/i,
  /^(姓名测试|算命|占卜|八字|风水|测名|起名|塔罗|面相)/i,
  /中文网|小说网|小说网|作文网/i,
  /^(学术|论文|期刊|文献|知网|万方|维普|文库|专利|学报)/i,
  /^(免责|声明|免责声明|免责申明|隐私|隐私协议|隐私政策|用户协议|服务协议|服务条款|TOS|ToS|CC协议|知识共享)/i,
  /^(学生邮箱|学校|校园|门户|信息门户|校园网|国科大|华农|SEP系统|邮箱|电子邮件)$/i,
  /^(博客集市|博客中心|博客圈|博客集|博客志|博友圈|博友)/i,
  /^(简历|个人简历|简历模板|简历网)/i,
  /^(视频剪辑|剪辑|手游|游戏下载|游戏网|游戏攻略)/i,
  /命令查询|命令大全|镜像|镜像站|Mirror/i,
  /^(排名|排行榜|编程语言排名|TIOBE)/i,
  /^(Waline|Twikoo|Giscus| utterances|Cusdis|Valine)/i,
	  /^(站点已过期|域名出售|域名停放|域名过期|site is for sale|domain is parked|this domain|buy this domain|备案过期|网站已关闭|网站已停止)/i,
	  /媒体娱乐应用|工作流编辑器|实时语音翻译/i,  // 产品功能/类型描述，非博客名称
	];
